// templates/next/src/app/examples/cards/components/notifications.tsx
"use client"

import { BellIcon, EyeNoneIcon, PersonIcon } from "@radix-ui/react-icons"

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"

export function DemoNotifications() {
  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle>Notifications</CardTitle>
        <CardDescription>
          Choose what you want to be notified about.
        </CardDescription>
      </CardHeader>
      <CardContent className="grid gap-1">
        <div className="-mx-2 flex items-start space-x-4 rounded-md p-2 transition-all hover:bg-accent hover:text-accent-foreground">
          <BellIcon className="mt-px h-5 w-5" />
          <div className="space-y-1">
            <p className="text-sm font-medium leading-none">Everything</p>
            <p className="text-sm text-muted-foreground">
              Email digest, mentions & all activity.
            </p>
          </div>
        </div>
        <div className="-mx-2 flex items-start space-x-4 rounded-md bg-accent p-2 text-accent-foreground transition-all">
          <PersonIcon className="mt-px h-5 w-5" />
          <div className="space-y-1">
            <p className="text-sm font-medium leading-none">Available</p>
            <p className="text-sm text-muted-foreground">
              Only mentions and comments.
            </p>
          </div>
        </div>
        <div className="-mx-2 flex items-start space-x-4 rounded-md p-2 transition-all hover:bg-accent hover:text-accent-foreground">
          <EyeNoneIcon className="mt-px h-5 w-5" />
          <div className="space-y-1">
            <p className="text-sm font-medium leading-none">Ignoring</p>
            <p className="text-sm text-muted-foreground">
              Turn off all notifications.
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

// templates/sveltekit/src/routes/cards/Notifications.svelte
<script lang="ts">
  import { AtSign, Bell, BellOff } from 'lucide-svelte';
  import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '$components/ui/card';
</script>

<Card>
  <CardHeader>
    <CardTitle>Notifications</CardTitle>
    <CardDescription>Choose what you want to be notified about.</CardDescription>
  </CardHeader>
  <CardContent class="grid gap-1 p-1.5">
    <div
      class="flex items-center space-x-4 rounded-md p-2 hover:bg-accent hover:text-accent-foreground"
    >
      <Bell class="h-5 w-5" />
      <div class="space-y-1">
        <p class="text-sm font-medium leading-none">Everything</p>
        <p class="text-sm text-muted-foreground">Email digest, mentions & all activity.</p>
      </div>
    </div>
    <div class="flex items-center space-x-4 rounded-md bg-accent p-2 text-accent-foreground">
      <AtSign class="h-5 w-5" />
      <div class="space-y-1">
        <p class="text-sm font-medium leading-none">Available</p>
        <p class="text-sm text-muted-foreground">Only mentions and comments.</p>
      </div>
    </div>
    <div
      class="flex items-center space-x-4 rounded-md p-2 hover:bg-accent hover:text-accent-foreground"
    >
      <BellOff class="h-5 w-5" />
      <div class="space-y-1">
        <p class="text-sm font-medium leading-none">Ignoring</p>
        <p class="text-sm text-muted-foreground">Turn off all notifications.</p>
      </div>
    </div>
  </CardContent>
</Card>
