// templates/sveltekit/src/lib/components/docs/nav/MainNav.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { docsConfig } from '$lib/config/docs';
  import { siteConfig } from '$lib/config/site';
  import { cn } from '$lib/utils';
  import { Icons } from '../icons';
</script>

<div class="mr-4 hidden md:flex">
  <a href="/" class="mr-6 flex items-center space-x-2">
    <Icons.logo class="h-6 w-6" />
    <span class="hidden font-bold sm:inline-block">
      {siteConfig.name}
    </span>
  </a>
  <nav class="flex items-center space-x-6 text-sm font-medium">
    {#each docsConfig.mainNav as navItem}
      <a
        href={navItem.href}
        class={cn(
          'transition-colors hover:text-foreground/80',
          $page.url.pathname === navItem.href ? 'text-foreground' : 'text-foreground/60'
        )}
        target={navItem.external ? '_blank' : undefined}
        rel={navItem.external ? 'noreferrer' : undefined}
      >
        {navItem.title}
      </a>
    {/each}
  </nav>
</div>

// templates/vite/src/dashboard/components/main-nav.tsx
import { cn } from "@/lib/utils"

export function MainNav({
  className,
  ...props
}: React.HTMLAttributes<HTMLElement>) {
  return (
    <nav
      className={cn("flex items-center space-x-4 lg:space-x-6", className)}
      {...props}
    >
      <a
        href="/examples/dashboard"
        className="text-sm font-medium transition-colors hover:text-primary"
      >
        Overview
      </a>
      <a
        href="/examples/dashboard"
        className="text-sm font-medium text-muted-foreground transition-colors hover:text-primary"
      >
        Customers
      </a>
      <a
        href="/examples/dashboard"
        className="text-sm font-medium text-muted-foreground transition-colors hover:text-primary"
      >
        Products
      </a>
      <a
        href="/examples/dashboard"
        className="text-sm font-medium text-muted-foreground transition-colors hover:text-primary"
      >
        Settings
      </a>
    </nav>
  )
}
